package edu.iastate.cs472.proj1;

import java.io.FileNotFoundException;

/**
 *  
 * @author
 *
 */

public class PuzzleSolver 
{
	/**
	 *  Read an initial state from the input file.  Solve the eight puzzle three times:
	 *  
	 *      1) The first solution allows single moves only and uses the heuristic based on the number
	 *         of mismatched tiles. 
	 *         
	 *      2) The second solution also allows single moves only but uses the heuristic based on the 
	 *         Manhattan distance. 
	 *         
	 *      3) The third solution allows single and double moves and uses the admissible heuristic 
	 *         designed by yourself.  
	 *         
	 *  Each solution is printed out as a sequence of states, generated by single/double moves, from the 
	 *  initial state to the goal state. If no solution exists, report it.  
	 * 
	 * @param args
	 * @throws FileNotFoundException if the input file does not exist 
	 * @throws IllegalArgumentException if the initial state from the file is not in the correct format
	 */
	public static void main(String[] args) throws FileNotFoundException, IllegalArgumentException
	{	
		// Read an initial board configuration from a file.  

		// Call EightPuzzle.solve8puzzle() to solve the puzzle. 
		
		// You may make it interactive by repeatedly accepting puzzle files and print out 
		// solutions.  (No extra credit but good for debugging and for the user.)
		String fileNames[] = new String[] {"8Puzzle.txt"}; 
		
		for (String fileName : fileNames) {
            try {
                System.out.println("Solving puzzle from file: " + fileName);
                
                // Step 1: Read the board configuration from the file
                State initialState = new State(fileName);  // Assuming State has a constructor that reads from a file
                System.out.println("Initial state:");
                System.out.println(initialState);  // Debug: Print the initial state

                // Step 2: Solve the puzzle with the first heuristic (TileMismatch)
                System.out.println("Solving with TileMismatch heuristic:");
				Heuristic h[] = {Heuristic.TileMismatch, Heuristic.ManhattanDist, Heuristic.DoubleMoveHeuristic }; 
                String solution1 = EightPuzzle.solve8Puzzle(initialState);
                System.out.println(solution1);

                // // Step 3: Solve the puzzle with the second heuristic (Manhattan Distance)
                // System.out.println("Solving with ManhattanDist heuristic:");
                // String solution2 = EightPuzzle.solve8Puzzle(initialState);
                // System.out.println(solution2);

                // // Step 4: Solve the puzzle with the third heuristic (Double Move Heuristic)
                // System.out.println("Solving with DoubleMoveHeuristic:");
                // String solution3 = EightPuzzle.solve8Puzzle(initialState);
                // System.out.println(solution3);

            } catch (FileNotFoundException e) {
                System.err.println("Error: File not found: " + fileName);
            } catch (IllegalArgumentException e) {
                System.err.println("Error: Invalid input format for file: " + fileName);
            }
        }
    }

}
