package edu.iastate.cs472.proj1;

import java.io.FileNotFoundException;

/**
 * Main class to solve 8-puzzle using A* algorithm with multiple heuristics.
 *
 * @author Kunle Oguntoye
 */
public class PuzzleSolver
{
	/**
	 *  Read an initial state from the input file.  Solve the eight puzzle three times:
	 *
	 *      1) The first solution allows single moves only and uses the heuristic based on the number
	 *         of mismatched tiles.
	 *
	 *      2) The second solution also allows single moves only but uses the heuristic based on the
	 *         Manhattan distance.
	 *
	 *      3) The third solution allows single and double moves and uses an admissible heuristic.
	 *
	 *  Each solution is printed out as a sequence of states, generated by single/double moves, from the
	 *  initial state to the goal state. If no solution exists, report it.
	 *
	 * @param args
	 * @throws FileNotFoundException if the input file does not exist
	 * @throws IllegalArgumentException if the initial state from the file is not in the correct format
	 */
	public static void main(String[] args) throws FileNotFoundException, IllegalArgumentException
	{
		String fileNames[] = new String[] {"8Puzzle.txt"}; 
		
		for (String fileName : fileNames) {
            try {
                System.out.println("Solving puzzle from file: " + fileName);
                System.out.println("=".repeat(50));

                // Read the board configuration from the file
                State initialState = new State(fileName);
                System.out.println("Initial state:");
                System.out.println(initialState);

                // Solve the puzzle using all three heuristics
                String solution = EightPuzzle.solve8Puzzle(initialState);
                System.out.println(solution);

            } catch (FileNotFoundException e) {
                System.err.println("Error: File not found: " + fileName);
            } catch (IllegalArgumentException e) {
                System.err.println("Error: Invalid input format for file: " + fileName);
            }
        }
    }

}
